name: 00 - Workflow Demo

on: 
  # push:
  #   branches: [ main ]
  #   paths: [ .github/workflows/0-demo.yaml ]
  workflow_dispatch:
  pull_request:
    branches: "main"
  schedule:
    - cron: "15 6 * * *"

run-name: "00 - Workflow Demo via ${{ github.event_name }} by ${{ github.actor }}"

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "Event: ${{ github.event_name }}"
          echo "Branch name is ${{ github.ref }}"
          
      - name: Checkout
        uses: actions/checkout@v3

      - name: List files in the repository
        run: |
          echo "The repository ${{ github.repository }} contains the following files:"
          tree
