name: 02 - Docker Action
on:
  push:
    branches: [ main ]
    paths: [ hello-world-docker-action/** ]
  workflow_dispatch:

jobs:
  test-action:
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2

      - name: Run my own container action
        id: hello-action
        uses: ./.github/actions/hello-world-action
        with:
          who-to-greet: '@renan-alm'

      - name: Output time set in the container
        run: echo "The time was ${{ steps.hello-action.outputs.time }} when the action said hello"
        
      - name: Write Summary Output
        run: | 
          echo "## Demo Summary Output :rocket:" >> $GITHUB_STEP_SUMMARY
          echo "The `time` from out custom action is ${{ steps.hello-action.outputs.time }}" >> $GITHUB_STEP_SUMMARY

      - name: Adding markdown
        run: echo '### Hello world! 🚀' >> $GITHUB_STEP_SUMMARY
      
      - run: echo "${{ steps.job-summary.outputs.job-summary }}"
