name: 07 - Cache Demo

on: [workflow_dispatch, push]

jobs:
  cache-job:
    name: Demo Cache
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2

      - name: Cache
        uses: actions/cache@v4.2.0
        id: cache
        with:
          path: cache-file
          key: ${{ runner.os }}-cache-demo

      - name: Generate Cache
        if: ${{ steps.cache.outputs.cache-hit == false }}
        run: echo "1 2 3..." > cache-file

      - name: Use Cache
        run: cat cache-file
