name: Workflow demo

on: 
  push:
  pull_request:
    branches: "main"
  schedule:
    - cron: "15 6 * * *"
    
jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "Event: ${{ github.event_name }}"
          echo "Branch name is ${{ github.ref }}"
          
      - name: Checkout
        uses: actions/checkout@v3

      - name: List files in the repository
        run: |
          echo "The repository ${{ github.repository }} contains the following files:"
          tree
