name: Demo

on: [push, pull_request, workflow_dispatch]

jobs:
  any-name:
    runs-on: ubuntu-latest
    steps:
      - name: Check my repo
        uses: actions/checkout@v4

      - name: Run a script
        run: print("Hello")
        shell: python
    
